# 服务注册中心
spring:
  application:
    name: register-center
server:
  port: 8761
eureka:
  client:
    # 检索服务选项, 当设置为 true(默认值) 时, 会进行服务检索,注册中心不负责检索服务
    fetch-registry: false
    # 服务注册中心也会将自己作为客户端来尝试注册自己, 为 true（默认）时自动生效
    register-with-eureka: false