# 服务注册中心
server:
  port: 8761

spring:
  application:
    name: register-center

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    # 检索服务选项, 当设置为 true(默认值) 时, 会进行服务检索,注册中心不负责检索服务
    fetch-registry: true
    # 服务注册中心也会将自己作为客户端来尝试注册自己, 为 true（默认）时自动生效
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/