server:
  port: 5000

spring:
  application:
    name: api-gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  routes:
    # 管理服务的路由
    problem:
      path: /api/manager/**
      serviceId: manager-service