# 路由网关
server:
  port: 80

spring:
  application:
    name: api-gateway
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://172.16.15.200:3306/cloud_oj}
    type: com.zaxxer.hikari.HikariDataSource
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      minimum-idle: 10
      maximum-pool-size: 50
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

mybatis:
  configuration:
    map-underscore-to-camel-case: on
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:127.0.0.1:8761}/eureka/

zuul:
  routes:
    # 管理服务
    manager:
      path: /api/manager/**
      serviceId: manager-service
    # 判题服务
    judge:
      path: /api/judge/**
      serviceId: judge-service
    # 文件服务
    file-server:
      path: /api/file/**
      serviceId: file-server
    # 前端
    web:
      path: /oj/**
      serviceId: cloud-oj-web

judge-service:
  ribbon:
    ReadTimeout: 6000

logging:
  file:
    name: /log/api-gateway.log

project:
  token-valid-time: 4