# 管理服务
server:
  port: 8001

spring:
  application:
    name: manager-service
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_oj?allowMultiQueries=true
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      minimum-idle: 10
      maximum-pool-size: 50
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

mybatis:
  configuration:
    map-underscore-to-camel-case: on
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


logging:
  level:
    top.cloudli: debug
  file:
    name: D:/cloud-oj/manager-service.log
