spring:
  application:
    name: monitor-service
  boot:
    admin:
      probed-endpoints: "*"

server:
  port: 5000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/