# 服务监控中心
server:
  port: 5000

spring:
  application:
    name: monitor-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
logging:
  file:
    name: /log/monitor-service.log
