server:
  port: 8000

spring:
  application:
    name: file-server
  boot:
    admin:
      client:
        url: http://localhost:5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

project:
  test-data-dir: D:/test_data/