server:
  port: 8080

spring:
  application:
    name: cloud-oj-web
  boot:
    admin:
      client:
        url: http://localhost:5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
