server:
  port: 8080
  tomcat:
    accept-count: ${TOMCAT_ACCEPT_COUNT:2000}
    max-threads: ${TOMCAT_MAX_THREADS:800}

spring:
  application:
    name: cloud-oj-web

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:127.0.0.1:8761}/eureka/

logging:
  file:
    name: /app/log/oj-web.log

project:
  gateway-host: ${GATEWAY_HOST:localhost}