version: '3.4'

services:
  oj-mysql:
    container_name: oj-mysql
    image: mysql:8.0.18
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "oj-mysql-data:/var/lib/mysql"
      - "./config:/etc/mysql/conf.d"
      - "./init:/docker-entrypoint-initdb.d"

volumes:
  oj-mysql-data: