spring:
  application:
    name: judge-service
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_oj
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      minimum-idle: 10
      maximum-pool-size: 50
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: cloud@oj
    password: cloud@oj

server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false


mybatis:
  configuration:
    map-underscore-to-camel-case: on
  mapper-locations: classpath:mybatis/mapper/*.xml

project:
  test-data-dir: D:/test_data/
  target-dir: D:/target/
